### PR TITLE
Fix security lint issues

### PR DESCRIPTION
**Pull request by hsingyuc**
Related P2 : https://wooengineering.wordpress.com/2022/12/05/automated-security-testing-of-woocommerce-extensions/?replytocom=1290#respond 

Plugin security issues file: https://docs.google.com/spreadsheets/d/1OcLUNrz99Ca_inYmlM_QVAk8FoczsQ1bioE31s7BYFI/edit#gid=0 

---

### Description
Fix the `UnsafePrintingFunction `, `OutputNotEscaped`, `NonceVerification`, `InputNotSanitized`, and the formatting errors.

### Steps to Test
* Go to the staging site https://zapaymentstaging.mystagingwebsite.com/ 
* Generally smoke test the plugin and make sure there are no regressions

### CODE REVIEW

**Review by leonardola — APPROVED** [review]
LGTM. Thanks for the fixes

**Comment by hsingyuc** [comment]
@jeffpaul Could you assign someone from 10up to review this PR? Thank you!

**Review by dkotter — APPROVED** [review]

**Comment by ankitguptaindia** [comment]
@iamdharmesh Could you please check and confirm you are also getting the same response in your [PayFast Sandbox account?](https://sandbox.payfast.co.za/)
After log-in to my sandbox account, I see the blank details in `Merchant ID` & `Merchant Key`

image

**Comment by ankitguptaindia** [comment]
> @iamdharmesh Could you please check and confirm you are also getting the same response in your [PayFast Sandbox account?](https://sandbox.payfast.co.za/) After log-in to my sandbox account, I see the blank details in `Merchant ID` & `Merchant Key`
> 

**Update -**  Something was wrong with the Sandbox account on that day. I opened Sandbox Dashboard with same user's credentials and 'Keys' are visible today.

Screenshot 2023-01-24 at 6 35 33 PM

**Comment by ankitguptaindia** [comment]
>Related P2 : https://wooengineering.wordpress.com/2022/12/05/automated-security-testing-of-woocommerce-extensions/?replytocom=1290#respond

>Plugin security issues file: https://docs.google.com/spreadsheets/d/1OcLUNrz99Ca_inYmlM_QVAk8FoczsQ1bioE31s7BYFI/edit#gid=0

>Go to the staging site https://zapaymentstaging.mystagingwebsite.com/


_Hi @hsingyuc Thanks for creating this PR. We don't have access to the above links and the site URL shared in the description. Please let us know if any important details are available in those links and should be cross-tested in our QA round._
BTW, I have tested this plugin on a fresh new setup, already running sites, simple products, subscription product purchases, and subscription renewal. All cases are working as expected and ITNs also getting added after each order in Sandbox Dashboard.


https://user-images.githubusercontent.com/6384299/214305530-8d12db2b-e9eb-4a1e-9a21-25af0875c96d.mp4

**Review by ankitguptaindia — APPROVED** [review]

**Comment by hsingyuc** [comment]
>We don't have access to the above links and the site URL shared in the description. Please let us know if any important details are available in those links and should be cross-tested in our QA round.

@ankitguptaindia Thank you for reviewing this PR.  You can skip the links.  They are for reference only.

**Comment by ankitguptaindia** [comment]
**Smoke Test Report-** ✅ 
-------

Tested with Archive File created via "php woorelease.phar build 'repo_URL' " 

- Composer version - 2.3.5
- npm version - 6.14.15
- node version - v14.18.0
- WordPress - 6.1.1
- WooCommerce - 7.3.0

### Please note that this plugin is tested with the build created by the specified versions of Composer, Node, and NPM. 



**Status-** Working expected with Plugin Archive/Zip file. Additionally, tested by overriding the old plugin file with a new file.

 


 **Next Step-** Ready to Merge 🚀

**Pull request merged**
