### PR TITLE
Tweak/deploy

### PR DESCRIPTION
**Pull request by roykho**
So I've added the necessary items for this extension to be woorelease ready and then some.

* Added build script so it can run several tasks like generate the language POT file automatically and also will generate the archive zip file.
* Added `// WRCS: DEFINED_VERSION.` comment to the constant version line so that woorelease can pick this up and bump the version for you as well.

After merge, to test: Run the develop branch of https://github.com/woocommerce/woocommerce-extension-release

It will default to simulation mode so nothing will be deployed.

### CODE REVIEW

**Comment by allendav** [comment]
Thanks for putting this together @roykho - I'm getting an unexpected error when attempting to run this, using the develop branch of woorelease:

```
allendav@Lyra woocommerce-extension-release % clear

allendav@Lyra woocommerce-extension-release % git status
On branch develop
Your branch is up to date with 'origin/develop'.

nothing to commit, working tree clean
allendav@Lyra woocommerce-extension-release % php woorelease.php https://github.com/woocommerce/woocommerce-gateway-payfast/tree/tweak/deploy
WR [21:38:23] Simulation mode. NO deploy actions will actually be taken.
WR [21:38:23] Woorelease initiated.
WR [21:38:23] Processing extension woocommerce-gateway-payfast...
WR [21:38:23] Attempting to clone extension...
WR [21:38:23] Re-attempting to clone extension.
WR [21:38:23] Executing: git clone --recurse-submodules https://github.com/woocommerce/woocommerce-gateway-payfast/tree/tweak/deploy.git 2>&1
WR [21:38:24] Cloning into 'deploy'...
WR [21:38:24] fatal: repository 'https://github.com/woocommerce/woocommerce-gateway-payfast/tree/tweak/deploy.git/' not found
WR [21:38:24] Error cloning extension 'woocommerce-gateway-payfast' from git
WR [21:38:24] Woodeploy finished with errors!
Please correct the error and retry or for more information on the error, please ping #extendables-support in Slack
allendav@Lyra woocommerce-extension-release % 
```

Any ideas?

**Comment by roykho** [comment]
@allendav can you try master branch and see if that works for you. Master branch of Payfast that is.

**Comment by allendav** [comment]
@roykho - it gets a little further

```
allendav@Lyra woocommerce-extension-release % php woorelease.php https://github.com/woocommerce/woocommerce-gateway-payfast                  
WR [22:10:49] Simulation mode. NO deploy actions will actually be taken.
WR [22:10:49] Woorelease initiated.
WR [22:10:49] Processing extension woocommerce-gateway-payfast...
WR [22:10:49] Attempting to clone extension...
WR [22:10:49] Re-attempting to clone extension.
WR [22:10:49] Executing: git clone --recurse-submodules https://github.com/woocommerce/woocommerce-gateway-payfast.git 2>&1
WR [22:10:49] Cloned to temporary directory: /var/folders/lf/r0n_ddjs6zl3c9kkpd7t1tj00000gn/T/woocommerce-gateway-payfast
WR [22:10:49] Checking out master branch.
WR [22:10:49] Executing: git checkout 'master' 2>&1
WR [22:10:49] Found extension slug for WordPress.org: 'woocommerce-payfast-gateway'. Following .org release process.
WR [22:10:49] Parsing changelog data...
WR [22:10:49] Using .org format
WR [22:10:49] Verifying latest version in changelog.txt matches readme.txt 'Stable tag'...
WR [22:10:49] 'Stable tag' version ('1.4.16') in readme.txt does not match latest version in changelog.txt ('1.4.15') for woocommerce-gateway-payfast.
WR [22:10:49] Woodeploy finished with errors!
Please correct the error and retry or for more information on the error, please ping #extendables-support in Slack
```

**Comment by roykho** [comment]
Yup it's working correctly now. I pinged you on the discrepancies of the versions.

So basically if your repo is all changed and ready to go, meaning you have all the versions set and you don't want woorelease to handle that for you, then you would run `woorelease.php woocommerce-gateway-payfast`

On the other hand if you want it to do the version bumping for you, you would run `woorelease.php --version=RELEASE_VERSION woocommerce-gateway-payfast`. But running it this way, it expects to see a changelog entry of the date that is partial such as `2020-xx-xx` so the script knows this is where to update the date "for today" and bump the version for it.

Let me know if that is more clear or I am happy to explain more.

**Comment by laurendavissmith** [comment]
@allendav any chance you can give this another shot with the 1.1.0 release so we can close this one out

**Comment by luizreis** [comment]
@roykho - thanks for working on this! I've rebased it with the latest changes and gave it a spin using the simulate command. All works well, but there's a new `languages` folder with the  `woocommerce-gateway-payfast.pot` file. I checked the current `.zip` from .org and it doesn't have that folder.

```
Your current build has added or removed files since the last release. Would you like to add/delete them in the svn working copy? [y/N] y
A         trunk/languages
A         trunk/languages/woocommerce-gateway-payfast.pot
```

I'm not that familiar with the .org deploys, so is this expected as part of the build script? Does it have any impact on users updating the plugin?

**Comment by roykho** [comment]
Yeah so it is customary to have a `languages` folder for WordPress plugins and it happens to be apart of the build script so I've included it here.

**Review by luizreis — APPROVED** [review]
> Yeah so it is customary to have a languages folder for WordPress plugins and it happens to be apart of the build script so I've included it here.

Awesome! Thank you for the quick reply 🚀. I'm approving this and will release `1.4.17` after merging it.

**Pull request merged**
