### PR TITLE
Update all dependencies

### PR DESCRIPTION
**Pull request by dkotter**
### Description

There are a number of open PRs from dependabot (and some we've already merged in) that update some dependencies in our dependency tree. Instead of handling these one by one, decided to open a single PR that updates everything. We don't include many dependencies ourselves and all the ones we include are `devDependencies`, that are used to compile assets.

This PR replaces:
- #56 
- #57 
- #58 
- #59 
- #74
- #79  
- #81 
- #82 
- #83 

### Steps to Test

1. Checkout this PR
2. If existing install, run `rm -rf node_modules` to start with a clean slate
3. Run `npm install`
4. Ensure any npm scripts work: `npm run build`, `npm run start:webpack`, `npm run lint:js`

Should notice some deprecation warnings when building assets. These should be addressed at some point but they shouldn't cause any issues right now.

In addition, the actual assets we use are for integrating with the WooCommerce Blocks plugin. These were added in #40, so I'd recommend following the testing instructions there. 

### Changelog Entry

> Fix - Update dependencies and fix some code styling.

### CODE REVIEW

**Review by Sidsector9 — APPROVED** [review]
Apologies for the super late review.

Scripts tested in the review:

- [x] build
- [x] start:webpack
- [x] lint:js
- [x] postbuild
- [x] postarchive
---
The `lint:js` script reported the error. `Error: Cannot find module 'prettier'`. I've added it to this PR.

**Comment by dkotter** [comment]
@ankitguptaindia Since we're just bumping dependency versions here, this can go straight to UAT once QA passes

**Comment by ankitguptaindia** [comment]
>The lint:js script reported the error. Error: Cannot find module 'prettier'. **I've added it to this PR.**

@Sidsector9 would like to confirm, is this addressed in current PR https://github.com/woocommerce/woocommerce-gateway-payfast/pull/61 ? 

I am getting some errors with `npm run lint:js` 

Screenshot 2022-04-25 at 8 27 04 PM

**Comment by Sidsector9** [comment]
@ankitguptaindia I don't remember, it's been a while since I've last worked on it.
@dkotter I added a `.prettierignore` file in [d871f15](https://github.com/woocommerce/woocommerce-gateway-payfast/pull/61/commits/d871f15dcd60fb7bbf3bccd0070e8507782a66bb) to exclude certain files from being formatted by Prettier.

All linting errors are cleared, Ankit you can test it.

**Comment by ankitguptaindia** [comment]
Thanks, @Sidsector9 for the fixes. `npm run lint:js` is also working without any error/warning now.

---

@dkotter As this is related to dependencies update. Moving this directly for Regression.

**Review by ankitguptaindia — APPROVED** [review]

**Comment by dkotter** [comment]
This is in the `testing` branch now

**Comment by ankitguptaindia** [comment]
Hello @dkotter @Sidsector9 

Before merging in `testing`,  `npm i` was working without any deprecated warnings but now I am seeing some warnings.
Is this due to any other PR?

FYI- I am using (Composer version 2.1.5, npm version 6.14.14, node version 12.8.0)

Screenshot 2022-05-10 at 5 37 15 PM

**Comment by Sidsector9** [comment]
@ankitguptaindia you can do either of the 2 things:

1. Delete `package-lock.json`. Use node 12.8.0 and run `npm i` so that it generates a new `package-lock.json` file for lockfileVersion@1
2. OR use node 16+ and run `npm i` so that it can use the existing `package-lock.json`

**Comment by dkotter** [comment]
@ankitguptaindia I've merged a few other dependency updates that came from dependabot and merged that all into `testing`. I don't see any errors when running `npm i` myself, either on the original branch or in `testing`.

I'm using composer v2.2.6, npm v8.1.3 and node v12.16.3.

Edit: but following up on what Sid mentions, the warnings you are getting won't cause any problems. They are either deprecation notices or a notice about an older npm version

**Comment by ankitguptaindia** [comment]
**Regression Test Report-**
------------

**Test Results -** Working expected with the `testing` branch. 
**Next Step-**   Ready to UAT.

**Review by ankitguptaindia — APPROVED** [review]

**Comment by ankitguptaindia** [comment]
Tested with Archive File created via "php woorelease.phar build repo_URL" (Composer version 2.1.5, npm version 6.14.14, node version 12.8.0)

**Status-** Working expected with Plugin Archive/Zip file same as fix specific branch. 


 **Next Step-** Ready to Merge 🚀

**Review by ankitguptaindia — APPROVED** [review]

**Pull request merged**
