### PR TITLE
Add support for custom order tables

### LINKED ISSUE #98: Test against Custom Order Table implementation
Describe the request
Please review the [Custom Order Table testing guide](https://developer.woocommerce.com/2022/05/16/call-for-early-testing-custom-order-table-migrations/), [upgrade guide](https://github.com/woocommerce/woocommerce/wiki/COT-Upgrade-Recipe-Book), and utilize the [latest testing ZIP](https://github.com/woocommerce/woocommerce/releases/tag/feature-custom-order-table) to see how the WooCommerce Core COT migration impacts the Payfast extension. If you run into questions, @alefesouza at WooCommerce will be the best person to reach out to while testing this migration on Payfast.

If things test smoothly, please leave a comment to that extent with any details of your testing.

If you run into issues, please document those here so that we can work with @alefesouza and the https://github.com/orgs/woocommerce/teams/proton team to determine if fixes are needed in WooCommerce core, Payfast, or both.

Testing approach:

Smoke test backend (wp-admin/management screens) interfaces to ensure they continue to work as expected.
Smoke test frontend functionality with Twenty Twenty-Two or Storefront.
By the nature of this project, think of any feature that might be related to how orders are stored in the database and prioritize testing that.

### PR DESCRIPTION
**Pull request by cadic**
### Description

This PR updates order meta workaround to specific WC_Order functions. 

Depends on #95, some code removes support of WooCommerce prior to 3.0.

### Steps to test

1. Create orders paid by Payfast without custom order tables
2. Perform custom order tables migration as described in [this blog post](https://developer.woocommerce.com/2022/05/16/call-for-early-testing-custom-order-table-migrations/)
3. Test create new order, view old and new orders, export orders.

### Documentation

- [ ] This PR needs documentation (has the "Documentation" label).

### Changelog Entry

> Add - Support for High-performance Order Storage ("HPOS") (formerly known as Custom Order Tables, "COT").

Closes #98

### CODE REVIEW

**Review by dkotter — APPROVED** [review]

**Comment by ankitguptaindia** [comment]
Hello @cadic Thanks for the PR, I am facing some issues when using the COT setup with this PR. 




1. Order details (Old orders + New Orders) page has Fatal error when using this PR. 

image


2. Pyafast Transaction ID is missing on new orders on COT setup.

COT setup - 
image

Non COT setup-

image

**Comment by ankitguptaindia** [comment]
QA Notes (for 10up QA use only)-  Other Order related functionalties are working expected. Tested!  

- Customer Details.  ✅ 
- Order Status by refunding  ✅ 
- Order Notes when ITNs updated  ✅ 
- Order Note to customers  ✅ 
- Order Notes when ITNs is in Pending Queue status  ✅ 
- Order Actions   ✅

**Comment by ankitguptaindia** [comment]
@cadic 
The first step in PR description has `Eway`. It looks like a Typo. Please also update the description.  Thanks!

> Create orders paid by Eway without custom order tables

**Comment by cadic** [comment]
@ankitguptaindia this is ready to re-test failing step

**Comment by ankitguptaindia** [comment]
**COT QA/Test Report-**
------------

**Testing Environment -** 

<Details>

* WordPress: 6.0.2
* Theme: Storefront Version: 4.1.3
* WooCommerce - [Version 6.9.0-dev](https://github.com/woocommerce/woocommerce/releases/tag/feature-custom-order-table) 
* PHP: 8.0.0 
* Web Server: Nginx
* Browser: Chrome - Version 102.0.5005.115
* OS: macOS Monterey V 12.3.1

</Details>



**Test Results -** Tested Order related functionality and performed various Use Cases. This extension-related functionality is working expected. 

Found some issues related to Woo Core (not related to this extension but affecting this extension functionality) and added them here. 

[#34490: [COT] Screen Options are not available on Single Order Screen](https://github.com/woocommerce/woocommerce/issues/34490)
[#34470: [COT] Fatal Error on adding Coupons to manual order](https://github.com/woocommerce/woocommerce/issues/34470)
[#34489: [COT] Order Preview icon does nothing on click](https://github.com/woocommerce/woocommerce/issues/34489)

**Next Step-** Ready to Code Review(Woo)

**Review by ankitguptaindia — APPROVED** [review]

**Review by alefesouza — APPROVED** [review]
LGTM

**Comment by ankitguptaindia** [comment]
**Regression Test Report-**
------------

**Testing Environment -** 




* WordPress: 6.0.2
* Theme: Storefront Version: 4.1.1
* WooCommerce - Version 6.9.4 stable & (Latest) 7.0.0-hpos.dev.4 [woocommerce.zip](https://github.com/woocommerce/woocommerce/files/9666854/woocommerce.zip)
* PHP: 8.0.0 
* Web Server: Nginx
* Browser: Chrome - Version 102.0.5005.115
* OS: macOS Monterey V 12.3.1
* Git Branch: `testing`






**Test Results -** Tested for Order Table with the latest Dev HPOS version and Post table with WC 6.9.4 latest stable version. All checks are found as working with `testing` branch. 

**Next Step-**   Ready to UAT.

**Comment by ankitguptaindia** [comment]
**Smoke Test Report-** ✅ 
-------

Tested with Archive File created via "php woorelease.phar build repo_URL" (Composer version 2.3.5, npm version 6.14.14, node version 12.8.0)

**Status-** Working expected with Plugin Archive/Zip file same as fix specific branch. 
Screenshot 2022-10-11 at 9 07 42 PM




 **Next Step-** Ready to Merge 🚀

**Pull request merged**
